---
apiVersion: xl-release/v1
kind: Templates
spec:
  - directory: Webhook Samples
    children:
      - name: Bitbucket Webhook Endpoint
        type: events.PostWebhookEndpoint
        path: bitbucket-sample-webhooks
        authentication:
          type: events.NoAuthentication
      - template: Bitbucket Sample Template
        scheduledStartDate: 2020-08-23T09:00:00-04:00
        dueDate: 2020-08-24T09:00:00-04:00
        phases:
          - phase: Demo
            tasks:
              - name: Display variables
                type: xlrelease.ScriptTask
                script: |-
                  variables = releaseApi.getVariables(release.id)
                  for var in variables:
                     print(var.key + ': ' + str(var.value))
            color: '#0079BC'
        variables:
          - type: xlrelease.StringVariable
            key: repository_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: branch_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_state
            requiresValue: false
          - type: xlrelease.StringVariable
            key: request_author
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_task_count
            requiresValue: false
          - type: xlrelease.MapStringStringVariable
            key: pull_request_map
            requiresValue: false
        scriptUsername: admin
        scriptUserPassword: admin
        riskProfile: Default risk profile
      - name: Bitbucket Push Event Trigger
        type: events.EventBasedTrigger
        description: Triggers on push to xlr-webhooks-sample:master
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: New Release created from push - ${event.push.changes[0].commits[0].message}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.full_name}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.push.changes[0].old.name}
          - type: xlrelease.StringValue
            targetProperty: variables[request_author]
            value: ${event.actor.display_name}
          - type: xlrelease.ListStringValue
            targetProperty: tags
            value:
              - ${event.push.changes[0].commits[0].date}
          - type: xlrelease.StringValue
            targetProperty: template
            value: Bitbucket Sample Template
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: Bitbucket Webhook Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.ExpressionEventFilter
          expressions:
            - type: events.EventFilterExpressionItem
              path: headers.['X-Event-Key']
              operator: EQUALS
              valueType: STRING
              value: repo:push
            - type: events.EventFilterExpressionItem
              path: event.repository.project.name
              operator: EQUALS
              valueType: STRING
              value: "test-project"
            - type: events.EventFilterExpressionItem
              path: event.repository.name
              operator: EQUALS
              valueType: STRING
              value: xlr-webhooks-sample
      - name: Bitbucket Pull Request Event Trigger
        type: events.EventBasedTrigger
        description: Triggers on pull request opened onto xlr-webhooks-samples:master
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: New Release from pull request ${event.pullrequest.rendered.title.raw}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.full_name}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.pullrequest.source.branch.name}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_state]
            value: ${event.pullrequest.state}
          - type: xlrelease.StringValue
            targetProperty: variables[request_author]
            value: ${event.pullrequest.author.display_name}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_task_count]
            value: ${event.pullrequest.task_count}
          - type: xlrelease.ListStringValue
            targetProperty: tags
            value:
              - ${event.pullrequest.updated_on}
          - type: xlrelease.StringValue
            targetProperty: template
            value: Bitbucket Sample Template
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: Bitbucket Webhook Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.GroovyEventFilter
          expr: "headers.'X-Event-Key' == 'pullrequest:created' && event.pullrequest.destination.branch.name == 'master' && event.repository.project.name == 'test-project'"