---
apiVersion: xl-release/v1
kind: Templates
spec:
  - directory: Webhook Samples
    children:
      - name: GitLab Webhook Endpoint
        type: events.PostWebhookEndpoint
        path: gitlab-sample-webhook
        authentication:
          type: events.NoAuthentication
      - template: GitLab Sample Template
        phases:
          - phase: Demo
            tasks:
              - name: Display variables
                type: xlrelease.ScriptTask
                script: |-
                  variables = releaseApi.getVariables(release.id)
                  for var in variables:
                     print(var.key + ': ' + str(var.value))
            color: '#0079BC'
        variables:
          - type: xlrelease.StringVariable
            key: repository_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: branch_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: merge_request_status
            requiresValue: false
          - type: xlrelease.StringVariable
            key: merge_request_author
            requiresValue: false
          - type: xlrelease.StringVariable
            key: merge_request_action
            requiresValue: false
          - type: xlrelease.StringVariable
            key: merge_request_assignees
            requiresValue: false
          - type: xlrelease.ListStringVariable
            key: merge_request_labels
            requiresValue: false
          - type: xlrelease.MapStringStringVariable
            key: merge_request_map
            requiresValue: false
        scriptUsername: admin
        scriptUserPassword: admin
        riskProfile: Default risk profile
      - name: GitLab Push Event Trigger
        type: events.EventBasedTrigger
        description: Triggers on push to xlr-webhooks-samples:master
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: Build GitLab Push - ${event.commits[-1:].title}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.name}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.project.default_branch}
          - type: xlrelease.ListStringValue
            targetProperty: tags
            value:
              - ${event.commits[-1:].timestamp}
          - type: xlrelease.StringValue
            targetProperty: template
            value: GitLab Sample Template
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: GitLab Webhook Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.ExpressionEventFilter
          expressions:
            - type: events.EventFilterExpressionItem
              path: headers.['X-Gitlab-Event']
              operator: EQUALS
              valueType: STRING
              value: Push Hook
            - type: events.EventFilterExpressionItem
              path: event.ref
              operator: INCLUDES
              valueType: STRING
              value: master
            - type: events.EventFilterExpressionItem
              path: event.repository.name
              operator: EQUALS
              valueType: STRING
              value: xlr-webhooks-samples
      - name: GitLab Merge Request Event Trigger
        type: events.EventBasedTrigger
        description: Triggers when a merge request, with BUILD label and merging into xlr-webhooks-samples:master, is opened or a commit has been added.
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: Build GitLab MR#${event.object_attributes.id} - ${event.object_attributes.title}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.name}
          - type: xlrelease.StringValue
            targetProperty: variables[merge_request_action]
            value: ${event.object_attributes.action}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.object_attributes.source_branch}
          - type: xlrelease.StringValue
            targetProperty: variables[merge_request_status]
            value: ${event.object_attributes.state}
          - type: xlrelease.StringValue
            targetProperty: variables[merge_request_author]
            value: ${event.user.name}
          - type: xlrelease.StringValue
            targetProperty: variables[merge_request_assignees]
            value: ${event.assignees..name}
          - type: xlrelease.VariableValue
            targetProperty: tags
            variableKey: event.labels..title
          - type: xlrelease.VariableValue
            targetProperty: variables[merge_request_map]
            variableKey: event.object_attributes
          - type: xlrelease.VariableValue
            targetProperty: variables[merge_request_labels]
            variableKey: event.labels..title
          - type: xlrelease.StringValue
            targetProperty: template
            value: GitLab Sample Template
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: GitLab Webhook Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.GroovyEventFilter
          expr: "headers.'X-Gitlab-Event' == 'Merge Request Hook' && \n\
                (event.object_attributes.action in ['opened', 'reopened'] || (event.object_attributes.action == 'update' && event.object_attributes.oldrev != null)) && \n\
                event.labels.title.contains('BUILD') && \n\
                event.object_attributes.target_branch == 'master' && \n\
                event.repository.name == 'xlr-webhooks-samples'"