---
apiVersion: xl-release/v1
kind: Templates
spec:
  - directory: Webhook Samples
    children:
      - name: Github Webhook Endpoint
        type: events.PostWebhookEndpoint
        path: github-sample-webhook
        authentication:
          type: events.NoAuthentication
      - template: Github Sample Template
        scheduledStartDate: 2020-07-23T09:00:00-04:00
        phases:
          - phase: Demo
            tasks:
              - name: Display variables
                type: xlrelease.ScriptTask
                script: |-
                  variables = releaseApi.getVariables(release.id)
                  for var in variables:
                     print(var.key + ': ' + str(var.value))
            color: '#0079BC'
        variables:
          - type: xlrelease.StringVariable
            key: repository_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: branch_name
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_status
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_author
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_action
            requiresValue: false
          - type: xlrelease.StringVariable
            key: pull_request_assignees
            requiresValue: false
          - type: xlrelease.ListStringVariable
            key: pull_request_labels
            requiresValue: false
          - type: xlrelease.MapStringStringVariable
            key: pull_request_map
            requiresValue: false
        scriptUsername: admin
        scriptUserPassword: admin
        riskProfile: Default risk profile
      - name: Github Push Event Trigger
        type: events.EventBasedTrigger
        description: Triggers on push to xlr-webhooks-samples:master
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: Build Github Push - ${event.head_commit.message}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.name}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.repository.default_branch}
          - type: xlrelease.ListStringValue
            targetProperty: tags
            value:
              - ${event.head_commit.timestamp}
          - type: xlrelease.StringValue
            targetProperty: template
            value: Github Sample Template
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: Github Webhook Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.ExpressionEventFilter
          expressions:
            - type: events.EventFilterExpressionItem
              path: headers.['X-GitHub-Event']
              operator: EQUALS
              valueType: STRING
              value: push
            - type: events.EventFilterExpressionItem
              path: event.ref
              operator: INCLUDES
              valueType: STRING
              value: master
            - type: events.EventFilterExpressionItem
              path: event.repository.name
              operator: EQUALS
              valueType: STRING
              value: xlr-webhooks-samples
      - name: Github Pull Request Event Trigger
        type: events.EventBasedTrigger
        description: Triggers on pull request with BUILD label opened onto xlr-webhooks-samples:master
        mappedProperties:
          - type: xlrelease.StringValue
            targetProperty: releaseTitle
            value: Build Github PR#${event.pull_request.number} - ${event.pull_request.title}
          - type: xlrelease.StringValue
            targetProperty: variables[repository_name]
            value: ${event.repository.name}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_action]
            value: ${event.action}
          - type: xlrelease.StringValue
            targetProperty: variables[branch_name]
            value: ${event.pull_request.head.ref}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_status]
            value: ${event.pull_request.state}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_author]
            value: ${event.sender.login}
          - type: xlrelease.StringValue
            targetProperty: variables[pull_request_assignees]
            value: ${event.requested_reviewer.login}
          - type: xlrelease.VariableValue
            targetProperty: tags
            variableKey: event.pull_request.labels..name
          - type: xlrelease.VariableValue
            targetProperty: variables[pull_request_map]
            variableKey: event.pull_request
          - type: xlrelease.VariableValue
            targetProperty: variables[pull_request_labels]
            variableKey: event.pull_request.labels..name
          - type: xlrelease.StringValue
            targetProperty: template
            value: Github Sample Template
        triggerActionType: xlrelease.CreateReleaseFromTemplateAction
        eventSource: Github Webhook Endpoint
        eventType: events.HttpRequestEvent
        eventFilter:
          type: events.GroovyEventFilter
          expr: "headers.'X-GitHub-Event' == 'pull_request' && \nevent.action in ['opened','reopened','syncronized'] &&\nevent.pull_request.labels.name.contains('\
        BUILD') && \nevent.pull_request.base.ref == 'master' &&\nevent.repository.name\
        \ == 'xlr-webhooks-samples'"
